spring.application.name=ESathi

##screte-key
#jwt.secret_key ="afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf";
#
#openweathermap.api.key=591490624bb84ccd21bbdd97367886a5
#gemini.api.key=AIzaSyB_29bEM5BmvRCvpDnpNkc-18qz58XNGxk
#gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
#
## zaror payy secre and key
#razorpay.key_id=rzp_test_lGxFPpDN5TVcjr
#razorpay.key_secret=Tfb9uzVCJKNgUmNJpxij85Kw

jwt.secret_key=${JWT_SECRET_KEY}

openweathermap.api.key=${OPENWEATHERMAP_API_KEY}

gemini.api.key=${GEMINI_API_KEY}
gemini.url=${GEMINI_API_URL}

razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}