spring.application.name=ESathi

openweathermap.api.key=591490624bb84ccd21bbdd97367886a5
gemini.api.key=AIzaSyB_29bEM5BmvRCvpDnpNkc-18qz58XNGxk
gemini.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro:generateContent?key=

# zaror payy secre and key
razorpay.key_id=rzp_test_lGxFPpDN5TVcjr
razorpay.key_secret=Tfb9uzVCJKNgUmNJpxij85Kw